spring:
  application:
    name: brokerage
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    hikari:
      pool-name: brokerage-hikari-pool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      auto-commit: true
      data-source-properties:
        useServerPrepStmts: true
        cachePrepStmts: true
        prepStmtCacheSize: 128
        prepStmtCacheSqlLimit: 2048
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
server:
  port: 8081
  servlet:
    context-path: /brokerage/api
application:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration: 86400000 # 24 hours in milliseconds
    refresh-expiration: 604800000 # 7 days
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin123}